INSERT INTO States (Name,Code) VALUES ('Acre', 'AC');
INSERT INTO States (Name,Code) VALUES ('Alagoas', 'AL');
INSERT INTO States (Name,Code) VALUES ('Amapá', 'AP');
INSERT INTO States (Name,Code) VALUES ('Amazonas', 'AM');
INSERT INTO States (Name,Code) VALUES ('Bahia', 'BA');
INSERT INTO States (Name,Code) VALUES ('Ceará', 'CE');
INSERT INTO States (Name,Code) VALUES ('Distrito Federal', 'DF');
INSERT INTO States (Name,Code) VALUES ('Espírito Santo', 'ES');
INSERT INTO States (Name,Code) VALUES ('Goiás', 'GO');
INSERT INTO States (Name,Code) VALUES ('Maranhão', 'MA');
INSERT INTO States (Name,Code) VALUES ('Mato Grosso', 'MT');
INSERT INTO States (Name,Code) VALUES ('Mato Grosso do Sul', 'MS');
INSERT INTO States (Name,Code) VALUES ('Minas Gerais', 'MG');
INSERT INTO States (Name,Code) VALUES ('Pará', 'PA');
INSERT INTO States (Name,Code) VALUES ('Paraiba', 'PB');
INSERT INTO States (Name,Code) VALUES ('Paraná', 'PR');
INSERT INTO States (Name,Code) VALUES ('Pernambuco', 'PE');
INSERT INTO States (Name,Code) VALUES ('Piauí', 'PI');
INSERT INTO States (Name,Code) VALUES ('Rio de Janeiro', 'RJ');
INSERT INTO States (Name,Code) VALUES ('Rio Grande do Norte', 'R');
INSERT INTO States (Name,Code) VALUES ('Rio Grande do Sul', 'RS');
INSERT INTO States (Name,Code) VALUES ('Rondônia', 'RO');
INSERT INTO States (Name,Code) VALUES ('Roraima', 'RR');
INSERT INTO States (Name,Code) VALUES ('Santa Catarina', 'SC');
INSERT INTO States (Name,Code) VALUES ('São Paulo', 'SP');
INSERT INTO States (Name,Code) VALUES ('Sergipe', 'SE');
INSERT INTO States (Name,Code) VALUES ('Tocantins', 'TO');