INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Acre', 'AC');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Alagoas', 'AL');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Amapá', 'AP');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Amazonas', 'AM');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Bahia', 'BA');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Ceará', 'CE');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Distrito Federal', 'DF');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Espírito Santo', 'ES');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Goiás', 'GO');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Maranhão', 'MA');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Mato Grosso', 'MT');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Mato Grosso do Sul', 'MS');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Minas Gerais', 'MG');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Pará', 'PA');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Paraiba', 'PB');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Paraná', 'PR');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Pernambuco', 'PE');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Piauí', 'PI');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Rio de Janeiro', 'RJ');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Rio Grande do Norte', 'R');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Rio Grande do Sul', 'RS');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Rondônia', 'RO');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Roraima', 'RR');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Santa Catarina', 'SC');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'São Paulo', 'SP');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Sergipe', 'SE');
INSERT INTO States (CreatedDate,Name,Code) VALUES (NOW(), 'Tocantins', 'TO');